<div id="header-box">
    <div id="module-status">
        <span class="viewsite"><a href="/" target="_blank"><?=$this->translate('View Site')?></a></span><span class="logout"><a href="/admin/user/logout"><?=$this->translate('Log out')?></a></span><span class="loggedin-users">1 <?=$this->translate('Logged-in backend')?></span>

    </div>

    <div id="module-menu">
        <ul id="menu" >

            <li class="node"><a class="" href="#"><?=$this->translate('Site')?></a>
                <ul>
                    <li><a class="icon-16-cpanel" href="/admin"><?=$this->translate('Control Panel')?></a></li>
                    <li class="separator"><span></span></li>
                    <li><a class="icon-16-config" href="/admin/config"><?=$this->translate('Global Configuration')?></a></li>
                    <li class="separator"><span></span></li>
                    <li><a class="icon-16-info" href="/admin/sysinfo"><?=$this->translate('System Information')?></a></li>
                    <li class="separator"><span></span></li>
                    <li><a class="icon-16-logout" href="/admin/user/logout"><?=$this->translate('Logout')?></a></li>
                </ul>
            </li>

            <li class="node"><a class="" href="#"><?=$this->translate('Users')?></a>
                <ul>
                    <li><a class="icon-16-user" href="/admin/user/list"><?=$this->translate('User Manager')?></a></li>
                    <li class="separator"><span></span></li>
                    <li><a class="icon-16-newuser" href="/admin/user/create"><?=$this->translate('Add New User')?></a></li>
                    <li><a class="icon-16-newgroup" href="/admin/usergroup/create"><?=$this->translate('Add New Group')?></a></li>
                    <li class="separator"><span></span></li>
                </ul>
            </li>

            <li class="node"><a class="" href="#"><?=$this->translate('Menus')?></a>
                <ul>
                    <li><a class="icon-16-menumgr" href="/admin/menu"><?=$this->translate('Menu Manager')?></a></li>
                    <li class="separator"><span></span></li>
                </ul>
            </li>

            <li class="node"><a class="" href="#"><?=$this->translate('Content')?></a>
                <ul>
                    <li><a class="icon-16-article" href="/admin/page"><?=$this->translate('Page Manager')?></a></li>
                    <li class="separator"><span></span></li>
                    <li><a class="icon-16-news" href="/admin/news"><?=$this->translate('News Manager')?></a></li>
                    <li><a class="icon-16-news" href="/admin/events"><?=$this->translate('Events Manager')?></a></li>
                    <li class="separator"><span></span></li>
                    <li><a href="/admin/insadvice" class="icon-16-article"><?=$this->translate('Advice Manager')?></a></li>
                    <li><a href="/admin/insblog" class="icon-16-article"><?=$this->translate('Blog Manager')?></a></li>
                    <li><a href="/admin/insarticle" class="icon-16-article"><?=$this->translate('Article Manager')?></a></li>
                    <li><a href="/admin/insgoods" class="icon-16-article"><?=$this->translate('Goods Manager')?></a></li>
                    <li><a href="/admin/insjob" class="icon-16-article"><?=$this->translate('Job Manager')?></a></li>
                    <li><a href="/admin/insprojects" class="icon-16-article"><?=$this->translate('Projects Manager')?></a></li>
                    <li><a href="/admin/insterm" class="icon-16-article"><?=$this->translate('Terms Manager')?></a></li>
                    <li><a href="/admin/insmaterials" class="icon-16-article"><?=$this->translate('Materials Manager')?></a></li>
                    <li><a href="/admin/insusers" class="icon-16-article"><?=$this->translate('Users Manager')?></a></li>
                </ul>
            </li>

        </ul>

    </div>
    <div class="clr"></div>
</div>