<div id="header-box">
    <div id="module-status">
        <span class="viewsite"><a href="/" target="_blank"><?=$this->translate('View Site')?></a></span><span class="logout"><a href="/admin/user/logout"><?=$this->translate('Log out')?></a></span><span class="loggedin-users">1 <?=$this->translate('Logged-in backend')?></span>

    </div>

    <div id="module-menu">
        <ul id="menu" >

            <li class="node"><a class="" href="#"><?=$this->translate('Site')?></a>
                <ul>
                    <li><a class="icon-16-cpanel" href="/admin"><?=$this->translate('Control Panel')?></a></li>
                    <li class="separator"><span></span></li>
                    <li><a class="icon-16-config" href="/admin/config"><?=$this->translate('Global Configuration')?></a></li>
                    <li class="separator"><span></span></li>
                    <li><a class="icon-16-info" href="/admin/sysinfo"><?=$this->translate('System Information')?></a></li>
                    <li class="separator"><span></span></li>
                    <li><a class="icon-16-logout" href="/admin/user/logout"><?=$this->translate('Logout')?></a></li>
                </ul>
            </li>

            <li class="node"><a class="" href="#"><?=$this->translate('Users')?></a>
                <ul>
                    <li><a class="icon-16-user" href="/admin/user/list"><?=$this->translate('User Manager')?></a></li>
                    <li class="separator"><span></span></li>
                    <li><a class="icon-16-newuser" href="/admin/user/create"><?=$this->translate('Add New User')?></a></li>
                    <li><a class="icon-16-newgroup" href="/admin/usergroup/create"><?=$this->translate('Add New Group')?></a></li>
                    <li class="separator"><span></span></li>
                </ul>
            </li>

            <li class="node"><a class="" href="#"><?=$this->translate('Menus')?></a>
                <ul>
                    <li><a class="icon-16-menumgr" href="/admin/menu"><?=$this->translate('Menu Manager')?></a></li>
                    <li class="separator"><span></span></li>
                </ul>
            </li>

            <li class="node"><a class="" href="#"><?=$this->translate('Content')?></a>
                <ul>
                    <li><a class="icon-16-article" href="/admin/page"><?=$this->translate('Page Manager')?></a></li>
<!--                    <li class="separator"><span></span></li>
                    <li><a class="icon-16-news" href="/admin/news"><?=$this->translate('News Manager')?></a></li>
                    <li><a class="icon-16-news" href="/admin/events"><?=$this->translate('Events Manager')?></a></li>-->
                    <li class="separator"><span></span></li>
                    <li><a href="/admin/ncuser" class="icon-16-news"><?=$this->translate("User Manager")?></a></li>
                    <li><a href="/admin/nccompany" class="icon-16-news"><?=$this->translate("Company Manager")?></a></li>
                    <li><a href="/admin/nctrademark" class="icon-16-news"><?=$this->translate("Trademark Manager")?></a></li>
                    <li><a href="/admin/ncgoods" class="icon-16-news"><?=$this->translate("Goods Manager")?></a></li>
                    <li><a href="/admin/ncmodel" class="icon-16-news"><?=$this->translate("Model Manager")?></a></li>
                    <li><a href="/admin/ncprojects" class="icon-16-news"><?=$this->translate("Projects Manager")?></a></li>
                    <li><a href="/admin/ncservice" class="icon-16-news"><?=$this->translate("Service Manager")?></a></li>
                    <li><a href="/admin/ncsupplier" class="icon-16-news"><?=$this->translate("Supplier Manager")?></a></li>
                    <li><a href="/admin/ncmaterial" class="icon-16-news"><?=$this->translate("Materials Manager")?></a></li>
                    <li><a href="/admin/ncarticle" class="icon-16-news"><?=$this->translate("Article Manager")?></a></li>
                    <li><a href="/admin/ncnews" class="icon-16-news"><?=$this->translate("News Manager")?></a></li>
                </ul>
            </li>
            <li class="node"><a class="" href="#"><?=$this->translate('Content cont.')?></a>
                <ul>
                    <li><a href="/admin/ncobject" class="icon-16-news"><?=$this->translate("Objects Manager")?></a></li>
                    <li><a href="/admin/ncstyle" class="icon-16-news"><?=$this->translate("Style Manager")?></a></li>
                    <li><a href="/admin/ncterm" class="icon-16-news"><?=$this->translate("Term Manager")?></a></li>
                    <li><a href="/admin/ncfamousauthor" class="icon-16-news"><?=$this->translate("Famous Authors Manager")?></a></li>
                    <li><a href="/admin/ncevents" class="icon-16-news"><?=$this->translate("Events Manager")?></a></li>
                    <li><a href="/admin/nclibrary" class="icon-16-news"><?=$this->translate("Library Manager")?></a></li>
                    <li><a href="/admin/nctender" class="icon-16-news"><?=$this->translate("Tender Manager")?></a></li>
                    <li><a href="/admin/ncconsultation" class="icon-16-news"><?=$this->translate("Consultation Manager")?></a></li>
                    <li><a href="/admin/nccountry" class="icon-16-news"><?=$this->translate("Countries Manager")?></a></li>
                    <li><a href="/admin/nccurrency" class="icon-16-news"><?=$this->translate("Currency Manager")?></a></li>
                    <li><a href="/admin/ncspecialization" class="icon-16-news"><?=$this->translate("Specialization Manager")?></a></li>
                    <li><a href="/admin/ncoffers" class="icon-16-news"><?=$this->translate("Offers Manager")?></a></li>
                </ul>
            </li>
        </ul>

    </div>
    <div class="clr"></div>
</div>