<?php $this->placeholder('toolbar-list')->captureStart();?>

<?php
echo $this->partial('partials/toolbar-list-buttons.phtml', array(
    'options' => array(
        'save' => array('tinymcetext' => 'detail_description'),
        'cancel' => array('uri' => '/admin/user/list')
    )
));
?>

<?php $this->placeholder('toolbar-list')->captureEnd();?>

<?php $this->placeholder('pagetitle')->captureStart();?>
<div class="pagetitle icon-48-user-add">
    <h2> <?=$this->translate('User Manager')?>: <?=$this->translate('Add New User')?> </h2>
</div>
<?php $this->placeholder('pagetitle')->captureEnd();?>

<?php $this->placeholder('element-box')->captureStart();?>

<?php
echo $this->partial('partials/_user-form.phtml', array('form' => $this->form));
?>

<?php $this->placeholder('element-box')->captureEnd();?>