<?php $this->placeholder('toolbar-list')->captureStart();?>
<!-- toolbar list content -->
<?php $this->placeholder('toolbar-list')->captureEnd();?>

<?php $this->placeholder('pagetitle')->captureStart();?>
<div class="pagetitle icon-48-user">
    <h2> <?=$this->translate('User Manager')?>: <?=$this->translate('My Account')?> </h2>
</div>
<?php $this->placeholder('pagetitle')->captureEnd();?>

<?php $this->placeholder('element-box')->captureStart();?>

<?php if($this->identity == null) { ?>
    <p><?=$this->translate('To log in')?> <a href='/admin/user/login'><?=$this->translate('click here')?></a></p>
<?php }else{ ?>
    <p><?=$this->translate('Welcome back')?>, <b><?php echo $this->identity->firstname;?></b></p>
    <p><?=$this->translate('To log out')?> <a href='/admin/user/logout'><?=$this->translate('click here')?></a></p>
<?php } ?>

<?php $this->placeholder('element-box')->captureEnd();?>

