<?php $this->placeholder('toolbar-list')->captureStart();?>

<?php
echo $this->partial('partials/toolbar-list-buttons.phtml', array(
    'options' => array(
        'buttons' => array('new', 'delete'),
        'new' => array('uri' => '/admin/user/create')
    )
));
?>

<?php $this->placeholder('toolbar-list')->captureEnd();?>

<?php $this->placeholder('pagetitle')->captureStart();?>
<div class="pagetitle icon-48-user">
    <h2> <?=$this->translate('User Manager')?>: <?=$this->translate('Users')?> </h2>
</div>
<?php $this->placeholder('pagetitle')->captureEnd();?>

<?php $this->placeholder('submenu')->captureStart();?>
<ul id="submenu">
    <li>
    <a class="active" href="/admin/user/list"><?=$this->translate('Users')?></a>
    </li>
    <li>
    </li>
    <li>
    </li>
</ul>
<?php $this->placeholder('submenu')->captureEnd();?>

<?php $this->placeholder('element-box')->captureStart();?>

<form name="adminForm" method="post" action="/admin/user/list">

    <fieldset id="filter-bar">
        <?php
        echo $this->partial('partials/search-filter.phtml');
        ?>
        <div class="filter-select fltrt">
        <label for="filter_enabled"> Filter Users by:  </label>
        <select class="inputbox" onchange="this.form.submit()" name="filter_enabled">
            <?php
            $options = array('options' => array(
                '*' => '- State',
                '1' => 'Enabled',
                '0' => 'Disabled'
                ), 'selected' => $this->filter['enabled']
            );
            echo $this->partial('partials/forms/select-options.phtml',
                    array('options' => $options));
            ?>
        </select>
        <select class="inputbox" onchange="this.form.submit()" name="filter_role">
            <?php
            $user_options = array('options' => array(
                '' => '- Group',
                'Administrator' => 'Administrator',
                'User' => 'User'
                ), 'selected' => $this->filter['role']
            );
            echo $this->partial('partials/forms/select-options.phtml',
                    array('options' => $user_options));
            ?>
        </select>
        </div>
    </fieldset>

    <div class="clr"> </div>

    <?php if(sizeof($this->paginator) > 0):?>

    <table class="adminlist">
        <thead>
            <tr>
                <th width="1%">
                    <input type="checkbox" onclick="checkAll(<?=count($this->users)?>)" value="" name="toggle"/>
                </th>
                <th class="left">
                    <a title="Click to sort by this column" href="<?php echo $this->getUrlReverseSorting(array(
                    'module' => 'admin',
                    'controller' => 'user',
                    'action' => 'list'
                 ), 'firstname');?>">
                    Name
                    <?php
                    echo $this->getSortImage('firstname');
                    ?>
                    </a>
                </th>
                <th class="nowrap" width="10%">
                    <a title="Click to sort by this column" href="<?php echo $this->getUrlReverseSorting(array(
                    'module' => 'admin',
                    'controller' => 'user',
                    'action' => 'list'
                 ), 'username');?>">User Name
                    <?php
                    echo $this->getSortImage('username');
                    ?>
                    </a>
                </th>
                <th class="nowrap" width="5%">
                    <a title="Click to sort by this column" href="<?php echo $this->getUrlReverseSorting(array(
                    'module' => 'admin',
                    'controller' => 'user',
                    'action' => 'list'
                 ), 'enabled');?>">Enabled
                    <?php
                    echo $this->getSortImage('enabled');
                    ?>
                    </a>
                </th>
                <th class="nowrap" width="10%"> Groups </th>
                <th class="nowrap" width="15%">
                    <a title="Click to sort by this column" href="<?php echo $this->getUrlReverseSorting(array(
                    'module' => 'admin',
                    'controller' => 'user',
                    'action' => 'list'
                 ), 'email');?>">E-mail
                    <?php
                    echo $this->getSortImage('email');
                    ?>
                    </a>
                </th>
                <th class="nowrap" width="15%">
                    <a title="Click to sort by this column" href="<?php echo $this->getUrlReverseSorting(array(
                    'module' => 'admin',
                    'controller' => 'user',
                    'action' => 'list'
                 ), 'lastvisitDate');?>">Last Visit Date
                    <?php
                    echo $this->getSortImage('lastvisitDate');
                    ?>
                    </a>
                </th>
                <th class="nowrap" width="15%">
                    <a title="Click to sort by this column" href="<?php echo $this->getUrlReverseSorting(array(
                    'module' => 'admin',
                    'controller' => 'user',
                    'action' => 'list'
                 ), 'registerDate');?>">Registration Date
                    <?php
                    echo $this->getSortImage('registerDate');
                    ?>
                    </a>
                </th>
                <th class="nowrap" width="3%">
                    <a title="Click to sort by this column" href="<?php echo $this->getUrlReverseSorting(array(
                    'module' => 'admin',
                    'controller' => 'user',
                    'action' => 'list'
                 ), 'id');?>">ID
                    <?php
                    echo $this->getSortImage('id');
                    ?>
                    </a>
                </th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="15">
                    <?php
                    echo $this->paginationControl($this->paginator,
                     'Sliding',
                     'partials/pagination-control.phtml');
                    ?>
                </td>
            </tr>
        </tfoot>
        <tbody>
            <?php
            echo $this->partialLoop('partials/_user-row.phtml', $this->paginator);
            ?>
        </tbody>
    </table>
    
    <input type="hidden" name="boxchecked" id="boxchecked" value="0" />
    <input type="hidden" name="order" value="<?php echo $this->orderParams['order']?>" />
    <input type="hidden" name="direction" value="<?php echo $this->orderParams['direction']?>" />

    <?else:?>
        You do not have any users
    <?endif;?>
    
</form>

<?php $this->placeholder('element-box')->captureEnd();?>
