<?php
echo $this->partial('partials/inspirate/category.phtml', array(
        'paginator' => $this->paginator,
        'section' => $this->translate('Project Manager'),
        'subsection' => $this->translate('Project Categories'),
        'itemUri' => '/admin/insproject',
        'catUri' => '/admin/insprojectcat',
        'itemName' => $this->translate('Project'),
        'itemController' => 'insprojectcat',
        'rowTpl' => '_projectcat-row.phtml'));