<?php
echo $this->partial('partials/inspirate/category.phtml', array(
        'paginator' => $this->paginator,
        'section' => $this->translate('Advice Manager'),
        'subsection' => $this->translate('Advice Categories'),
        'itemUri' => '/admin/insadvice',
        'catUri' => '/admin/insadvicecat',
        'itemName' => $this->translate('Advices'),
        'itemController' => 'insadvicecat',
        'rowTpl' => '_advicecat-row.phtml'));