<?php
echo $this->partial('partials/inspirate/category.phtml', array(
        'paginator' => $this->paginator,
        'section' => $this->translate('Blog Manager'),
        'subsection' => $this->translate('Blog Categories'),
        'itemUri' => '/admin/insblog',
        'catUri' => '/admin/insblogcat',
        'itemName' => $this->translate('Blogs'),
        'itemController' => 'insblogcat',
        'rowTpl' => '_blogcat-row.phtml'));