<ul id="menu">
<?php
foreach ($this->container as $page) {
    ?>
    <li
        <?if(true === $page->active):?> class="<?=$page->getClass()?>"<?endif;?>
        >
    <?php
    echo $this->navigation()->menu()->htmlify($page);
    ?>
        <span></span>
    <?php
    if(count($page->getPages()) > 0 && (true === $page->active)):
    ?>
        <ul style="display:block;">
        <?php
        foreach($page->getPages() as $childPage) {
            ?>
            <li>
            <?php
                echo $this->navigation()->menu()->htmlify($childPage);
            ?>
            </li>
            <?php
        }
        ?>
        </ul>
    <?php
    endif;
    ?>
    </li>
    <?php
}
?>
</ul>
