<?php foreach($this->news as $singleNews):?>
<div class="one">
  <?php if(!empty($singleNews['previewPhoto'])):?>
    <img alt="" src="<?=htmlspecialchars($singleNews['previewPhoto'])?>" />
  <?endif;?>
  <p><a href="/<?=$this->pageurl?>/id/<?=$singleNews['id']?>/"><?=$this->escape($singleNews['name'])?></a></p>
  <p><?=$this->escape($singleNews['anonce'])?></p>
  <p class="date"><?=$this->getLocalizedDate($singleNews['date'])?>, <?=$singleNews['city']?></p>
</div>
<?endforeach;?>