<?php if ($this->pageCount > 1) {?>

<div class="pager">
<!-- Previous page link -->
<?php if (isset($this->previous)){ ?>
  <div class="arr-l"><a href="<?php echo $this->pageurl; ?>?page=<?=$this->previous?>">
    <img src="/skins/frontend/images/arr-l.png" alt="" />
  </a></div>
<?php } else { ?>
  <div class="arr-l"><img src="/skins/frontend/images/arr-l.png" alt="" /></div>
<?php }?>
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page){ ?>
  <?php if ($page != $this->current){ ?>
    <span>
        <a href="<?php echo $this->pageurl; ?>?page=<?=$page?>">
             <?php echo $page; ?>
        </a>
    </span>
  <?php } else { ?>
    <span><?php echo $page; ?></span>
  <?php }}?>
<!-- Next page link -->
<?php if (isset($this->next)){ ?>
  <div class="arr-r">
    <a href="<?php echo $this->pageurl; ?>?page=<?=$this->next?>">
        <img src="/skins/frontend/images/arr-r.png" alt="" />
    </a>
  </div>
<?php } else { ?>
  <div class="arr-r"><img src="/skins/frontend/images/arr-r.png" alt="" /></div>
<?php } ?>
</div>
<?php } ?>