<?php $this->placeholder('toolbar-list')->captureStart();?>

<?php
echo $this->partial('partials/toolbar-list-buttons.phtml', array(
    'options' => array(
        'save' => array('tinymcetext' => 'content'),
        'cancel' => array('uri' => '/admin/page')
    )
));
?>

<?php $this->placeholder('toolbar-list')->captureEnd();?>

<?php $this->placeholder('pagetitle')->captureStart();?>
<div class="pagetitle icon-48-article">
    <h2> <?=$this->translate('Page Manager')?>: <?=$this->translate('Edit Page')?> </h2>
</div>
<?php $this->placeholder('pagetitle')->captureEnd();?>

<?php $this->placeholder('element-box')->captureStart();?>

<?php
echo $this->partial('partials/_page-form.phtml', array(
        'form' => $this->form,
        'skin' => $this->skin,
        'nodes' => $this->nodes
     ));
?>

<?php $this->placeholder('element-box')->captureEnd();?>