<?php
echo $this->partial('partials/inspirate/category.phtml', array(
        'paginator' => $this->paginator,
        'section' => $this->translate('Job Manager'),
        'subsection' => $this->translate('Job Categories'),
        'itemUri' => '/admin/insjob',
        'catUri' => '/admin/insjobcat',
        'itemName' => $this->translate('Job'),
        'itemController' => 'insjobcat',
        'rowTpl' => '_jobcat-row.phtml'));