<?php $this->placeholder('toolbar-list')->captureStart();?>

<?php
echo $this->partial('partials/toolbar-list-buttons.phtml', array(
    'options' => array(
        'save' => array('tinymcetext' => 'detail_description'),
        'cancel' => array('uri' => '/admin/events')
    )
));
?>

<?php $this->placeholder('toolbar-list')->captureEnd();?>

<?php $this->placeholder('pagetitle')->captureStart();?>
<div class="pagetitle icon-48-news-add">
    <h2> <?=$this->translate('Events Manager')?>: <?=$this->translate('Add Events')?> </h2>
</div>
<?php $this->placeholder('pagetitle')->captureEnd();?>

<?php $this->placeholder('element-box')->captureStart();?>

<?php
echo $this->partial('partials/_events-form.phtml', array('form' => $this->form, 'skin' => $this->skin));
?>

<?php $this->placeholder('element-box')->captureEnd();?>