<?php $this->placeholder('toolbar-list')->captureStart();?>

<?php
echo $this->partial('partials/toolbar-list-buttons.phtml', array(
    'options' => array(
        'buttons' => array('new', 'delete'),
        'new' => array('uri' => '/admin/events/create')
    )
));
?>

<?php $this->placeholder('toolbar-list')->captureEnd();?>

<?php $this->placeholder('pagetitle')->captureStart();?>
<div class="pagetitle icon-48-news">
    <h2> <?=$this->translate('Events Manager')?>: <?=$this->translate('Events')?> </h2>
</div>
<?php $this->placeholder('pagetitle')->captureEnd();?>

<?php $this->placeholder('submenu')->captureStart();?>
<ul id="submenu">
    <li>
    <a class="active" href="/admin/events"><?=$this->translate('Events')?></a>
    </li>
    <li>
    </li>
    <li>
    </li>
</ul>
<?php $this->placeholder('submenu')->captureEnd();?>

<?php $this->placeholder('element-box')->captureStart();?>
<form name="adminForm" method="post" action="/admin/events">
    <fieldset id="filter-bar">
        <?php
        echo $this->partial('partials/search-filter.phtml');
        ?>
        <div class="filter-select fltrt">
            <select class="inputbox" onchange="this.form.submit()" name="filter_published">
                <?php
                $options = array('options' => array(
                    '*' => '- Select State -',
                    '1' => 'Published',
                    '0' => 'Unpublished'
                    ), 'selected' => $this->filter['published']
                );
                echo $this->partial('partials/forms/select-options.phtml',
                        array('options' => $options));
                ?>
            </select>
        </div>
    </fieldset>
    <div class="clr"> </div>
        <table class="adminlist">
            <thead>
                <tr>
                    <th width="1%">
                        <input type="checkbox" onclick="checkAll(this)" value="" name="toggle"/>
                    </th>
                    <th>
                        <a title="Click to sort by this column" href="<?php echo $this->getUrlReverseSorting(array(
                        'module' => 'admin',
                        'controller' => 'events',
                        'action' => 'index'
                     ), 'title');?>">
                        Title
                        <?php
                        echo $this->getSortImage('title');
                        ?>
                        </a>
                    </th>
                    <th width="5%">
                        <a title="Click to sort by this column" href="<?php echo $this->getUrlReverseSorting(array(
                        'module' => 'admin',
                        'controller' => 'news',
                        'action' => 'index'
                     ), 'published');?>">
                        Published
                        <?php
                        echo $this->getSortImage('published');
                        ?>
                        </a>
                    </th>
                    <th width="10%">
                        Category
                    </th>
                    <th class="nowrap" width="10%">
                        <a title="Click to sort by this column" href="<?php echo $this->getUrlReverseSorting(array(
                        'module' => 'admin',
                        'controller' => 'news',
                        'action' => 'index'
                     ), 'lft');?>">
                        Ordering
                        <?php
                        echo $this->getSortImage('lft');
                        ?>
                        </a>
                        <a title="Save Order" href="javascript:saveorder(1, 'articles.saveorder')">
                        <img alt="Save Order" src="/skins/<?=$this->skin?>/images/admin/filesave.png"/>
                        </a>
                    </th>
                    <th width="10%">
                        Created by
                    </th>
                    <th width="5%">
                        Date
                    </th>
                    <th width="5%">
                        Hits
                    </th>
                    <th class="nowrap" width="1%">
                        <a title="Click to sort by this column" href="<?php echo $this->getUrlReverseSorting(array(
                        'module' => 'admin',
                        'controller' => 'news',
                        'action' => 'index'
                     ), 'id');?>">
                        ID
                        <?php
                        echo $this->getSortImage('id');
                        ?>
                        </a>
                    </th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td colspan="15">
                        <?php
                        echo $this->paginationControl($this->paginator,
                         'Sliding',
                         'partials/pagination-control.phtml');
                        ?>
                    </td>
                </tr>
            </tfoot>
            <tbody>
                <?php
                echo $this->partialLoop('partials/_events-row.phtml', $this->paginator );
                ?>
            </tbody>
        </table>
    <input type="hidden" name="boxchecked" id="boxchecked" value="0" />
</form>
<?php $this->placeholder('element-box')->captureEnd();?>