<?php $this->placeholder('toolbar-list')->captureStart();?>

<?php
echo $this->partial('partials/toolbar-list-buttons.phtml', array(
    'options' => array(
        'cancel' => array('uri' => '/admin/menuitem')
    )
));
?>

<?php $this->placeholder('toolbar-list')->captureEnd();?>

<?php $this->placeholder('pagetitle')->captureStart();?>
<div class="pagetitle icon-48-menu-add">
    <h2> <?=$this->translate('Menu Manager')?>: <?=$this->translate('Edit Menu Item')?></h2>
</div>
<?php $this->placeholder('pagetitle')->captureEnd();?>

<?php $this->placeholder('element-box')->captureStart();?>

<?php
echo $this->partial('partials/_menuitem-form.phtml', array('form' => $this->form, 'menus' => $this->menus));
?>

<?php $this->placeholder('element-box')->captureEnd();?>
