<?php $this->placeholder('toolbar-list')->captureStart();?>

<?php
echo $this->partial('partials/toolbar-list-buttons.phtml', array(
    'options' => array(
        'buttons' => array('new', 'delete'),
        'new' => array('uri' => '/admin/menuitem/create')
    )
));
?>

<?php $this->placeholder('toolbar-list')->captureEnd();?>

<?php $this->placeholder('pagetitle')->captureStart();?>
<div class="pagetitle icon-48-menumgr">
    <h2> <?=$this->translate('Menu Manager')?>: <?=$this->translate('Menu Items')?> </h2>
</div>
<?php $this->placeholder('pagetitle')->captureEnd();?>

<?php $this->placeholder('submenu')->captureStart();?>
<ul id="submenu">
    <li>
        <a href="/admin/menu">Menus</a>
    </li>
    <li>
        <a class="active" href="/admin/menuitem"><?=$this->translate('Menu Items')?></a>
    </li>
</ul>
<?php $this->placeholder('submenu')->captureEnd();?>

<?php $this->placeholder('element-box')->captureStart();?>

<form name="adminForm" method="post" action="/admin/menuitem">

    <fieldset id="filter-bar">
        <?php
        echo $this->partial('partials/search-filter.phtml');
        ?>
        <div class="filter-select fltrt">
            <select class="inputbox" onchange="this.form.submit()" name="filter_state">
                <?php
                $options = array('options' => array(
                    '*' => '- Select State -',
                    '1' => 'Published',
                    '0' => 'Unpublished'
                    ), 'selected' => $this->filter['state']
                );
                echo $this->partial('partials/forms/select-options.phtml',
                        array('options' => $options));
                ?>
            </select>
            <select class="inputbox" onchange="this.form.submit()" name="filter_menuid">
                <?php
                $options = array(
                    'options' => array('' => '- Select Menu Type -')
                        + $this->menus,
                    'selected' => $this->filter['menuid']);
                echo $this->partial('partials/forms/select-options.phtml',
                        array('options' => $options));
                ?>
            </select>
            <select class="inputbox" onchange="this.form.submit()" name="filter_level">
                <?php
                $options = array(
                    'options' => array('' => '- Select Menu Level -')
                        + $this->menuLevels,
                    'selected' => $this->filter['level']);
                echo $this->partial('partials/forms/select-options.phtml',
                        array('options' => $options));
                ?>
            </select>
        </div>
    </fieldset>
    <div class="clr"> </div>
    <table class="adminlist">
        <thead>
            <tr>
                <th width="1%">
                    <input type="checkbox" onclick="checkAll(this)" value="" name="toggle"/>
                </th>
                <th class="title">
                    <a title="Click to sort by this column" href="<?php echo $this->getUrlReverseSorting(array(
                    'module' => 'admin',
                    'controller' => 'menuitem',
                    'action' => 'index'
                 ), 'label');?>">
                    Title
                    <?php
                    echo $this->getSortImage('label');
                    ?>
                    </a>
                </th>
                <th class="nowrap" width="15%">
                    <a title="Click to sort by this column" href="<?php echo $this->getUrlReverseSorting(array(
                    'module' => 'admin',
                    'controller' => 'menuitem',
                    'action' => 'index'
                 ), 'uri');?>">
                    Uri
                    <?php
                    echo $this->getSortImage('uri');
                    ?>
                    </a>
                </th>
                <th width="5%">
                    <a title="Click to sort by this column" href="<?php echo $this->getUrlReverseSorting(array(
                    'module' => 'admin',
                    'controller' => 'menuitem',
                    'action' => 'index'
                 ), 'published');?>">
                    Published
                    <?php
                    echo $this->getSortImage('published');
                    ?>
                    </a>
                </th>
                <th class="nowrap" width="13%">
                    <a title="Click to sort by this column" href="<?php echo $this->getUrlReverseSorting(array(
                    'module' => 'admin',
                    'controller' => 'menuitem',
                    'action' => 'index'
                 ), 'lft');?>">
                    Ordering
                    <?php
                    echo $this->getSortImage('lft');
                    ?>
                    </a>
                    <a title="Save Order" href="javascript:saveorder(9, 'saveorder')">
                        <img alt="Save Order" src="/skins/<?=$this->skin?>/images/admin/filesave.png"/>
                    </a>
                </th>
                <th width="10%"> Menu Item Location </th>
                <th class="nowrap" width="1%">
                    <a title="Click to sort by this column" href="<?php echo $this->getUrlReverseSorting(array(
                    'module' => 'admin',
                    'controller' => 'menuitem',
                    'action' => 'index'
                 ), 'id');?>">
                    ID
                    <?php
                    echo $this->getSortImage('id');
                    ?>
                    </a>
                </th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="15">
                    <?php
                    echo $this->paginationControl($this->paginator,
                     'Sliding',
                     'partials/pagination-control.phtml');
                    ?>
                </td>
            </tr>
        </tfoot>
        <tbody>
            <?php
            echo $this->partialLoop('partials/_menuitem-row.phtml', $this->paginator );
            ?>
        </tbody>
    </table>
    <input type="hidden" name="boxchecked" id="boxchecked" value="0" />
</form>
<?php $this->placeholder('element-box')->captureEnd();?>