<form action="<?=$this->form->getAction()?>"
      method="<?=$this->form->getMethod()?>"
      id="<?=$this->form->getAttrib('id')?>"
      class="<?=$this->form->getAttrib('class')?>"
      name="<?=$this->form->getName()?>"
      >
    <div class="width-60 fltlft">
        <fieldset class="adminform">
            <legend><?=$this->translate('Details')?></legend>
            <ul class="adminformlist">
                <li>
                    <label id="label-lb" for="label" class="required">
                        <?=$this->translate('Label')?>
                    </label>
                    <?=$this->form->label?>
                </li>
                <li>
                    <label id="uri-lbl" for="uri" class="required">
                        <?=$this->translate('Uri')?>
                    </label>
                    <?=$this->form->uri?>
                </li>
                <li>
                    <label id="position-lbl" for="position">
                        <?=$this->translate('Position')?>
                    </label>
                    <?=$this->form->position?>
                </li>
                <li>
                    <label id="parent_id-lbl" for="parent_id">
                        <?=$this->translate('Parent Menu Item')?>
                    </label>
                    <?=$this->form->parent_id?>
                </li>
                <li>
                    <label id="published-lbl" for="published">
                        <?=$this->translate('Published')?>
                    </label>
                    <fieldset id="published" class="radio">
                    <?php
                    echo $this->partial('partials/radiobutton-control.phtml', array(
                        'options' => $this->form->published->getMultiOptions(),
                        'selected' => $this->form->published->getValue(),
                        'name' => 'published'
                    ));
                    ?>
                    </fieldset>
                </li>
                <li>
                    <label id="menuId-lbl" for="menu_id" class="required">
                        <?=$this->translate('Menu Location')?>
                    </label>
                    <?=$this->form->menu_id?>
                </li>
            </ul>
        </fieldset>
    </div>


    <?=$this->form->id?>
</form>
<div class="clr"></div>
<div class="clr"></div>