<div class="noshow">
    <div class="width-100">
        <fieldset class="adminform">
            <legend><?=$this->translate('System Information')?></legend>
            <table class="adminlist">
                <thead>
                    <tr>
                        <th width="250"> <?=$this->translate('Setting')?> </th>
                        <th> <?=$this->translate('Value')?> </th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <td colspan="2">  </td>
                    </tr>
                </tfoot>
                <tbody>
                    <tr>
                        <td>
                            <strong><?=$this->translate('PHP Built On')?>:</strong>
                        </td>
                        <td> <?=$this->sysInfo->phpRunningOnInfo()?> </td>
                    </tr>
                    <tr>
                        <td>
                            <strong><?=$this->translate('Database Version')?>:</strong>
                        </td>
                        <td> <?=$this->sysInfo->dbVersion()?> </td>
                    </tr>
                    <tr>
                        <td>
                            <strong><?=$this->translate('Database Collation')?>:</strong>
                        </td>
                        <td> <?=$this->sysInfo->databaseCollation()?> </td>
                    </tr>
                    <tr>
                        <td>
                            <strong><?=$this->translate('Connection Collation')?>:</strong>
                        </td>
                        <td> <?=$this->sysInfo->connectionCollation()?> </td>
                    </tr>
                   <tr>
                        <td>
                            <strong><?=$this->translate('Server Collation')?>:</strong>
                        </td>
                        <td> <?=$this->sysInfo->serverCollation()?> </td>
                    </tr>
                    <tr>
                        <td>
                            <strong><?=$this->translate('PHP Version')?>:</strong>
                        </td>
                        <td> <?=$this->sysInfo->phpVersion()?> </td>
                    </tr>
                    <tr>
                        <td>
                            <strong><?=$this->translate('Web Server')?>:</strong>
                        </td>
                        <td> <?=$this->sysInfo->webServer()?> </td>
                    </tr>
                    <tr>
                        <td>
                            <strong><?=$this->translate('WebServer to PHP Interface')?>:</strong>
                        </td>
                        <td> <?=$this->sysInfo->phpSapiName()?> </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>Soulex! <?=$this->translate('Version')?>:</strong>
                        </td>
                        <td> <?=$this->sysInfo->systemVersion()?> </td>
                    </tr>
                    <tr>
                        <td>
                            <strong><?=$this->translate('User Agent')?>:</strong>
                        </td>
                        <td> <?=$this->sysInfo->userAgent()?> </td>
                    </tr>
                </tbody>
            </table>
        </fieldset>
    </div>
</div>