<div class="noshow">
    <div class="width-60">
        <fieldset class="adminform">
            <legend><?=$this->translate('Configuration File')?></legend>
            <table class="adminlist">
                <thead>
                    <tr>
                        <th width="250"> <?=$this->translate('Setting')?> </th>
                        <th> <?=$this->translate('Value')?> </th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <td colspan="2">  </td>
                    </tr>
                </tfoot>
                <tbody>
                    <tr>
                        <td> <?=$this->translate('db adapter')?> </td>
                        <td> <?=$this->sysInfo->configSetting('resources.db.adapter')?> </td>
                    </tr>
                    <tr>
                        <td> <?=$this->translate('host')?> </td>
                        <td> xxxxxx </td>
                    </tr>
                    <tr>
                        <td> <?=$this->translate('user')?> </td>
                        <td> xxxxxx </td>
                    </tr>
                    <tr>
                        <td> <?=$this->translate('password')?> </td>
                        <td> xxxxxx </td>
                    </tr>
                    <tr>
                        <td> <?=$this->translate('db')?> </td>
                        <td> <?=$this->sysInfo->configSetting('resources.db.params.dbname')?> </td>
                    </tr>
                    <tr>
                        <td> <?=$this->translate('Include paths library')?> </td>
                        <td> <?=$this->sysInfo->configSetting('includePaths.library')?> </td>
                    </tr>
                    <tr>
                        <td> <?=$this->translate('Bootstrap path')?> </td>
                        <td> <?=$this->sysInfo->configSetting('bootstrap.path')?> </td>
                    </tr>
                    <tr>
                        <td> <?=$this->translate('Bootstrap class')?> </td>
                        <td> <?=$this->sysInfo->configSetting('bootstrap.class')?> </td>
                    </tr>
                    <tr>
                        <td> <?=$this->translate('Controller Directory')?> </td>
                        <td> <?=$this->sysInfo->configSetting('resources.frontController.controllerDirectory')?> </td>
                    </tr>
                    <tr>
                        <td> <?=$this->translate('Layout path')?> </td>
                        <td> <?=$this->sysInfo->configSetting('resources.layout.layoutPath')?> </td>
                    </tr>
                    <tr>
                        <td> <?=$this->translate('Layout')?> </td>
                        <td> <?=$this->sysInfo->configSetting('resources.layout.layout')?> </td>
                    </tr>
                    <tr>
                        <td> <?=$this->translate('Modules directory')?> </td>
                        <td> <?=$this->sysInfo->configSetting('resources.frontController.moduleDirectory')?> </td>
                    </tr>
                    <tr>
                        <td> <?=$this->translate('Front controller plugins')?> </td>
                        <td> <?=$this->sysInfo->configSetting('resources.frontController.plugins')?> </td>
                    </tr>
                </tbody>
            </table>
        </fieldset>
    </div>
</div>
