<form action="<?=$this->form->getAction()?>"
      method="<?=$this->form->getMethod()?>"
      id="<?=$this->form->getAttrib('id')?>"
      class="<?=$this->form->getAttrib('class')?>"
      name="<?=$this->form->getName()?>"
      autocomplete="off"
      >
          <div class="width-60 fltlft">
            <fieldset class="adminform">
                <legend><?=$this->translate('Account Details')?></legend>
                <ul class="adminformlist">
                    <li>
                        <label id="title-lbl" for="title" class="required">
                            <?=$this->translate('User Name')?>
                        </label>
                        <?=$this->form->username?>
                    </li>
                    <li>
                        <label id="firstname-lbl" for="firstname">
                            <?=$this->translate('First Name')?>
                        </label>
                        <?=$this->form->firstname?>
                    </li>
                    <li>
                        <label id="lastname-lbl" for="lastname">
                            <?=$this->translate('Last Name')?>
                        </label>
                        <?=$this->form->lastname?>
                    </li>
                    <li>
                        <label id="password-lbl" for="password">
                            <?=$this->translate('Password')?>
                        </label>
                        <?=$this->form->password?>
                    </li>
                    <li>
                        <label id="confirmPassword-lbl" for="confirmPassword">
                            <?=$this->translate('Confirm Password')?>
                        </label>
                        <?=$this->form->confirmPassword?>
                    </li>
                    <li>
                        <label id="email-lbl" for="email" class="required">Email</label>
                        <?=$this->form->email?>
                    </li>
                    <li>
                        <label id="enabled-lbl" for="enabled">
                            <?=$this->translate('Block this User')?>
                        </label>
                        <fieldset class="radio" id="userform_block">
                            <?php
                            echo $this->partial('partials/radiobutton-control.phtml', array(
                                'options' => $this->form->enabled->getMultiOptions(),
                                'selected' => $this->form->enabled->getValue(),
                                'name' => 'enabled'
                            ));
                            ?>
                        </fieldset>
                    </li>
                    <li>
                        <label id="registerDate-lbl" for="registerDate">
                            <?=$this->translate('Registration Date')?>
                        </label>
                        <?=$this->form->registerDate?>
                    </li>
                    <li>
                        <label id="lastvisitDate-lbl" for="lastvisitDate">
                            <?=$this->translate('Last visit Date')?>
                        </label>
                        <?=$this->form->lastvisitDate?>
                    </li>
                </ul>
            </fieldset>

            <fieldset class="adminform" id="user-groups">
                <legend><?=$this->translate('Assigned Groups')?></legend>
                <?=$this->form->role?>
            </fieldset>

          </div>
    <?=$this->form->id?>
</form>
