<h1>Обратная связь</h1>

<form action="<?=$this->form->getAction()?>"
      method="<?=$this->form->getMethod()?>"
      id="<?=$this->form->getAttrib('id')?>"
      name="<?=$this->form->getName()?>"
      >
        <?=$this->form->name?>
        <?=$this->form->email?>
        <?=$this->form->tel?>
        <?=$this->form->theme?>
        <?=$this->form->text?>
        <?=$this->form->captcha?>
        <?=$this->form->csrf?>
        <?=$this->form->submit?>
</form>
<?php
if(null !== $this->messageSent) {
    ?>
    <p>
        Спасибо! Ваше сообщение было отправлено.
    </p>
    <?php
}
?>