<?php $this->placeholder('toolbar-list')->captureStart();?>

<?php
echo $this->partial('partials/toolbar-list-buttons.phtml', array(
    'options' => array(
        'cancel' => array('uri' => '/admin/insadvice')
    )
));
?>

<?php $this->placeholder('toolbar-list')->captureEnd();?>

<?php $this->placeholder('pagetitle')->captureStart();?>
<div class="pagetitle icon-48-menu">
    <h2> <?=$this->translate('Advice Manager')?>: <?=$this->translate('Add New Advice')?> </h2>
</div>
<?php $this->placeholder('pagetitle')->captureEnd();?>

<?php $this->placeholder('element-box')->captureStart();?>

<?php
echo $this->partial('partials/inspirate/_advice-form.phtml', array('form' => $this->form));
?>

<?php $this->placeholder('element-box')->captureEnd();?>
