<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
  <head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <?php
    echo $this->headTitle();
    echo $this->headScript();
    $this->loadSkin($this->skin);
    echo $this->headLink();
	echo $this->headMeta();
    ?>
    <script src="/skins/<?=$this->skin?>/js/jquery-1.4.4.min.js" type="text/javascript"></script>
    <script src="/skins/<?=$this->skin?>/js/jquery-ui-1.8.9.custom.min.js" type="text/javascript"></script>
    <script src="/skins/<?=$this->skin?>/js/jquery.livequery.js" type="text/javascript"></script>
    <script src="/skins/<?=$this->skin?>/js/jquery.masonry.js" type="text/javascript"></script>
    <script src="/skins/<?=$this->skin?>/js/jquery.fancybox-1.3.4.pack.js" type="text/javascript"></script>
    <script src="/skins/<?=$this->skin?>/js/application.js" type="text/javascript"></script>

    <link rel="shortcut icon" href="/skins/<?=$this->skin?>/images/favicon.ico" />

  </head>
<body>
<div id="cont">
    <?=$this->layout()->favorite;?>
<!-- top -->
    <?=$this->render('frontend/top.phtml');?>
<!-- /top -->
<!-- CENTER -->
  <div class="center">
<!-- left-block -->
    <div class="left-block">
<!-- menu-left -->
    <?=$this->layout()->menuleft;?>
<!-- /menu-left -->
      <div class="banner">
        <a href="#"><img src="/skins/<?=$this->skin?>/images/banner/banner5.png" alt="" /></a>
      </div>

      <?=$this->layout()->block1?>

      <?=$this->layout()->block2?>

      <?=$this->layout()->block3?>

      <?=$this->layout()->block4?>

      <?=$this->layout()->block6?>

      <div class="rss">
        <p><a href="#">RSS подписка на объекты</a></p>
      </div>
    </div>
<!-- /left-block -->

<!-- right-block -->
      <div class="right-block">
          <?=$this->layout()->block5?>
      </div>
<!-- /right-block -->
    <div class="clear"></div>
  </div>
<!-- /CENTER -->
</div>

  <?=$this->render('frontend/footer.phtml');?>
</body>
</html>