<form action="<?=$this->form->getAction()?>"
      method="<?=$this->form->getMethod()?>"
      id="<?=$this->form->getAttrib('id')?>"
      class="<?=$this->form->getAttrib('class')?>"
      name="<?=$this->form->getName()?>"
      >
    <div class="width-60 fltlft">
        <fieldset class="adminform">
            <legend><?=$this->translate('Advice Details')?></legend>
            <ul class="adminformlist">
                <li>
                    <label id="name-lbl" for="name" class="required">
                        <?=$this->translate('Name')?>
                    </label>
                    <?=$this->form->name?>
                </li>
                <li>
                    <label id="date-lbl" for="date" class="required">
                        <?=$this->translate('Date')?>
                    </label>
                    <?=$this->form->date?>
                </li>
                <li>
                    <label id="teaser-lbl" for="teaser">
                        <?=$this->translate('Teaser')?>
                    </label>
                    <?=$this->form->teaser?>
                </li>
                <li>
                    <label for="file" id="file-lbl">
                        <?=$this->translate('File');?>
                    </label>
                    <?=$this->form->file;?>
                </li>
                <li>
                    <label for="category" id="category-lbl">
                        <?=$this->translate('Category');?>
                    </label>
                    <?=$this->form->cat_id;?>
                </li>
                <li>
                    <label for="user" id="user-lbl">
                        <?=$this->translate('User');?>
                    </label>
                    <?=$this->form->user_id;?>
                </li>
                <li>
                    <label for="draft" id="draft-lbl">
                        <?=$this->translate('Draft');?>
                    </label>
                    <fieldset id="draft" class="radio">
                    <?php
                    echo $this->partial('partials/radiobutton-control.phtml', array(
                        'options' => $this->form->draft->getMultiOptions(),
                        'selected' => $this->form->draft->getValue(),
                        'name' => 'draft'
                    ));
                    ?>
                    </fieldset>
                </li>
            </ul>
            <div class="clr"></div>
            <div id="content-node">
                    <label for="text" id="text-lbl">
                        <?=$this->translate('Text');?>
                    </label>
                    <div class="clr"></div>
                    <?=$this->form->text;?>
                    <div class="toggle-editor">
                        <div class="button2-left">
                            <div class="blank">
                                <a title="Toggle editor" onclick="javascript:tinyMCE.execCommand('mceToggleEditor', false, 'text');return false;" href="#"><?=$this->translate('Toggle editor')?></a>
                            </div>
                        </div>
                    </div>
            </div>
        </fieldset>
    </div>

    <?=$this->form->id?>
</form>
<div class="clr"></div>
<div class="clr"></div>