<tr class="row<?php echo $this->partialCounter % 2 == 0 ? 1 : 0?>">
    <td class="center">
        <input id="cb0" type="checkbox" title="Checkbox for row <?=$this->partialCounter?>" onclick="isChecked(this.checked);" value="<?=$this->id?>" name="cid[]"/>
    </td>
    <td>
        <a href="/admin/insnewscat/edit/id/<?=$this->id?>">
            <?=$this->escape($this->name)?>
        </a>
    </td>
    <td class="center"> <?=$this->id?> </td>
</tr>