<?php $this->placeholder('toolbar-list')->captureStart();?>

<?php
echo $this->partial('partials/toolbar-list-buttons.phtml', array(
    'options' => array(
        'buttons' => array('new', 'delete'),
        'new' => array('uri' => $this->catUri . '/create')
    )
));
?>

<?php $this->placeholder('toolbar-list')->captureEnd();?>

<?php $this->placeholder('pagetitle')->captureStart();?>
<div class="pagetitle icon-48-menumgr">
    <h2> <?=$this->section?>: <?=$this->subsection?> </h2>
</div>
<?php $this->placeholder('pagetitle')->captureEnd();?>

<?php $this->placeholder('submenu')->captureStart();?>
<ul id="submenu">
    <li>
        <a href="<?=$this->itemUri?>"><?=$this->itemName?></a>
    </li>
    <li>
        <a class="active" href="<?=$this->catUri?>"><?=$this->subsection?></a>
    </li>
</ul>
<?php $this->placeholder('submenu')->captureEnd();?>

<?php $this->placeholder('element-box')->captureStart();?>

<form name="adminForm" method="post" action="<?=$this->catUri?>">

    <fieldset id="filter-bar">
        <?php
        echo $this->partial('partials/search-filter.phtml');
        ?>
    </fieldset>
    <div class="clr"> </div>
    <table class="adminlist">
        <thead>
            <tr>
                <th width="1%">
                    <input type="checkbox" onclick="checkAll(this)" value="" name="toggle"/>
                </th>
                <th class="title">
                    <a title="Click to sort by this column" href="<?php echo $this->getUrlReverseSorting(array(
                    'module' => 'admin',
                    'controller' => $this->itemController,
                    'action' => 'index'
                 ), 'name');?>">
                    <?php
                    echo $this->translate("Name");
                    echo $this->getSortImage('name');
                    ?>
                    </a>
                </th>
                <th class="nowrap" width="1%">
                    <a title="Click to sort by this column" href="<?php echo $this->getUrlReverseSorting(array(
                    'module' => 'admin',
                    'controller' => $this->itemController,
                    'action' => 'index'
                 ), 'id');?>">
                    ID
                    <?php
                    echo $this->getSortImage('id');
                    ?>
                    </a>
                </th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="15">
                    <?php
                    echo $this->paginationControl($this->paginator,
                     'Sliding',
                     'partials/pagination-control.phtml');
                    ?>
                </td>
            </tr>
        </tfoot>
        <tbody>
            <?php
            echo $this->partialLoop('partials/inspirate/' . $this->rowTpl, $this->paginator);
            ?>
        </tbody>
    </table>
    <input type="hidden" name="boxchecked" id="boxchecked" value="0" />
</form>
<?php $this->placeholder('element-box')->captureEnd();?>
