<form action="<?=$this->form->getAction()?>"
      method="<?=$this->form->getMethod()?>"
      id="<?=$this->form->getAttrib('id')?>"
      class="<?=$this->form->getAttrib('class')?>"
      name="<?=$this->form->getName()?>"
      >
    <div class="width-60 fltlft">
        <fieldset class="adminform">
            <legend><?=$this->details?></legend>
            <ul class="adminformlist">
                <li>
                    <label id="name-lbl" for="name" class="required">
                        <?=$this->translate('Name')?>
                    </label>
                    <?=$this->form->name?>
                </li>
            </ul>
        </fieldset>
    </div>

    <?=$this->form->id?>
</form>
<div class="clr"></div>
<div class="clr"></div>