<?php
echo $this->partial('partials/inspirate/category.phtml', array(
        'paginator' => $this->paginator,
        'section' => $this->translate('News Manager'),
        'subsection' => $this->translate('News Categories'),
        'itemUri' => '/admin/insnews',
        'catUri' => '/admin/insnewscat',
        'itemName' => $this->translate('News'),
        'itemController' => 'insnewscat',
        'rowTpl' => '_newscat-row.phtml'));